"""add_unique_active_session_index

Revision ID: 621aa6c6d813
Revises: b30bb576b11d
Create Date: 2026-10-03 13:51:31.796737+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '621aa6c6d813'
down_revision: Union[str, None] = 'b30bb576b11d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_study_sessions_user_active', 'study_sessions', ['user_id'], unique=True, postgresql_where=sa.text("status = 'active'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_study_sessions_user_active', table_name='study_sessions', postgresql_where=sa.text("status = 'active'"))
    # ### end Alembic commands ###
