"""initial_schema

Revision ID: b30bb576b11d
Revises: 
Create Date: 2026-10-03 08:55:11.274169+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b30bb576b11d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('auth_identities',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_subject', sa.String(length=255), nullable=False),
    sa.Column('provider_email', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint("provider IN ('google', 'local')", name=op.f('ck_auth_identities_ck_auth_identities_provider')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_auth_identities_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auth_identities')),
    sa.UniqueConstraint('provider', 'provider_subject', name='uq_auth_identities_provider_subject')
    )
    op.create_index(op.f('ix_auth_identities_user_id'), 'auth_identities', ['user_id'], unique=False)
    op.create_table('study_sessions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total_duration_seconds', sa.Float(), nullable=False),
    sa.Column('focused_seconds', sa.Float(), nullable=False),
    sa.Column('distracted_seconds', sa.Float(), nullable=False),
    sa.Column('away_seconds', sa.Float(), nullable=False),
    sa.Column('focus_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('detector_version', sa.String(length=20), nullable=False),
    sa.Column('feature_schema_version', sa.String(length=30), nullable=False),
    sa.Column('calibration_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('active', 'completed', 'cancelled')", name=op.f('ck_study_sessions_ck_study_sessions_status')),
    sa.CheckConstraint('away_seconds >= 0', name=op.f('ck_study_sessions_ck_study_sessions_away_seconds_non_negative')),
    sa.CheckConstraint('distracted_seconds >= 0', name=op.f('ck_study_sessions_ck_study_sessions_distracted_seconds_non_negative')),
    sa.CheckConstraint('ended_at IS NULL OR ended_at >= started_at', name=op.f('ck_study_sessions_ck_study_sessions_time_consistency')),
    sa.CheckConstraint('focus_score IS NULL OR (focus_score >= 0 AND focus_score <= 100)', name=op.f('ck_study_sessions_ck_study_sessions_focus_score_range')),
    sa.CheckConstraint('focused_seconds >= 0', name=op.f('ck_study_sessions_ck_study_sessions_focused_seconds_non_negative')),
    sa.CheckConstraint('total_duration_seconds >= 0', name=op.f('ck_study_sessions_ck_study_sessions_total_duration_non_negative')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_study_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_study_sessions'))
    )
    op.create_index(op.f('ix_study_sessions_started_at'), 'study_sessions', ['started_at'], unique=False)
    op.create_index(op.f('ix_study_sessions_status'), 'study_sessions', ['status'], unique=False)
    op.create_index(op.f('ix_study_sessions_user_id'), 'study_sessions', ['user_id'], unique=False)
    op.create_index('ix_study_sessions_user_started', 'study_sessions', ['user_id', 'started_at'], unique=False)
    op.create_table('user_settings',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('looking_away_delay_seconds', sa.Float(), nullable=False),
    sa.Column('phone_use_delay_seconds', sa.Float(), nullable=False),
    sa.Column('yawning_delay_seconds', sa.Float(), nullable=False),
    sa.Column('drowsy_delay_seconds', sa.Float(), nullable=False),
    sa.Column('leaning_back_delay_seconds', sa.Float(), nullable=False),
    sa.Column('away_from_desk_delay_seconds', sa.Float(), nullable=False),
    sa.Column('sound_alerts_enabled', sa.Boolean(), nullable=False),
    sa.Column('banner_alerts_enabled', sa.Boolean(), nullable=False),
    sa.Column('session_end_summary_enabled', sa.Boolean(), nullable=False),
    sa.Column('camera_device', sa.String(length=100), nullable=False),
    sa.Column('preview_quality', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('away_from_desk_delay_seconds >= 0', name=op.f('ck_user_settings_ck_user_settings_away_from_desk_delay')),
    sa.CheckConstraint('drowsy_delay_seconds >= 0', name=op.f('ck_user_settings_ck_user_settings_drowsy_delay')),
    sa.CheckConstraint('leaning_back_delay_seconds >= 0', name=op.f('ck_user_settings_ck_user_settings_leaning_back_delay')),
    sa.CheckConstraint('looking_away_delay_seconds >= 0', name=op.f('ck_user_settings_ck_user_settings_looking_away_delay')),
    sa.CheckConstraint('phone_use_delay_seconds >= 0', name=op.f('ck_user_settings_ck_user_settings_phone_use_delay')),
    sa.CheckConstraint('yawning_delay_seconds >= 0', name=op.f('ck_user_settings_ck_user_settings_yawning_delay')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_settings_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_settings')),
    sa.UniqueConstraint('user_id', name='uq_user_settings_user_id')
    )
    op.create_index(op.f('ix_user_settings_user_id'), 'user_settings', ['user_id'], unique=True)
    op.create_table('detection_events',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=30), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('detector_version', sa.String(length=20), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint("event_type IN ('looking_away', 'phone_use', 'yawning', 'drowsy', 'leaning_back', 'away_from_desk')", name=op.f('ck_detection_events_ck_detection_events_type')),
    sa.CheckConstraint('duration_seconds IS NULL OR duration_seconds >= 0', name=op.f('ck_detection_events_ck_detection_events_duration_non_negative')),
    sa.CheckConstraint('ended_at IS NULL OR ended_at >= started_at', name=op.f('ck_detection_events_ck_detection_events_time_consistency')),
    sa.ForeignKeyConstraint(['session_id'], ['study_sessions.id'], name=op.f('fk_detection_events_session_id_study_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_detection_events'))
    )
    op.create_index(op.f('ix_detection_events_event_type'), 'detection_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_detection_events_session_id'), 'detection_events', ['session_id'], unique=False)
    op.create_index('ix_detection_events_session_started', 'detection_events', ['session_id', 'started_at'], unique=False)
    op.create_index('ix_detection_events_session_type', 'detection_events', ['session_id', 'event_type'], unique=False)
    op.create_index(op.f('ix_detection_events_started_at'), 'detection_events', ['started_at'], unique=False)
    op.create_table('telemetry_samples',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('sampled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('frame_index', sa.Integer(), nullable=True),
    sa.Column('detector_version', sa.String(length=20), nullable=False),
    sa.Column('feature_schema_version', sa.String(length=30), nullable=False),
    sa.Column('head_pitch', sa.Float(), nullable=True),
    sa.Column('head_yaw', sa.Float(), nullable=True),
    sa.Column('head_roll', sa.Float(), nullable=True),
    sa.Column('ear', sa.Float(), nullable=True),
    sa.Column('mar', sa.Float(), nullable=True),
    sa.Column('min_hand_cheek_distance', sa.Float(), nullable=True),
    sa.Column('shoulder_z', sa.Float(), nullable=True),
    sa.Column('face_present', sa.Boolean(), nullable=True),
    sa.Column('pose_present', sa.Boolean(), nullable=True),
    sa.Column('hand_count', sa.Integer(), nullable=True),
    sa.Column('focus_state', sa.String(length=20), nullable=True),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint('frame_index IS NULL OR frame_index >= 0', name=op.f('ck_telemetry_samples_ck_telemetry_samples_frame_index')),
    sa.ForeignKeyConstraint(['session_id'], ['study_sessions.id'], name=op.f('fk_telemetry_samples_session_id_study_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_telemetry_samples'))
    )
    op.create_index(op.f('ix_telemetry_samples_sampled_at'), 'telemetry_samples', ['sampled_at'], unique=False)
    op.create_index(op.f('ix_telemetry_samples_session_id'), 'telemetry_samples', ['session_id'], unique=False)
    op.create_index('ix_telemetry_samples_session_sampled', 'telemetry_samples', ['session_id', 'sampled_at'], unique=False)
    op.create_table('session_feedback',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('detection_event_id', sa.UUID(), nullable=True),
    sa.Column('feedback_type', sa.String(length=30), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint("feedback_type IN ('correct_detection', 'false_positive', 'missed_detection', 'other')", name=op.f('ck_session_feedback_ck_session_feedback_type')),
    sa.ForeignKeyConstraint(['detection_event_id'], ['detection_events.id'], name=op.f('fk_session_feedback_detection_event_id_detection_events'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['study_sessions.id'], name=op.f('fk_session_feedback_session_id_study_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_session_feedback'))
    )
    op.create_index(op.f('ix_session_feedback_detection_event_id'), 'session_feedback', ['detection_event_id'], unique=False)
    op.create_index('ix_session_feedback_session_event', 'session_feedback', ['session_id', 'detection_event_id'], unique=False)
    op.create_index(op.f('ix_session_feedback_session_id'), 'session_feedback', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_session_feedback_session_id'), table_name='session_feedback')
    op.drop_index('ix_session_feedback_session_event', table_name='session_feedback')
    op.drop_index(op.f('ix_session_feedback_detection_event_id'), table_name='session_feedback')
    op.drop_table('session_feedback')
    op.drop_index('ix_telemetry_samples_session_sampled', table_name='telemetry_samples')
    op.drop_index(op.f('ix_telemetry_samples_session_id'), table_name='telemetry_samples')
    op.drop_index(op.f('ix_telemetry_samples_sampled_at'), table_name='telemetry_samples')
    op.drop_table('telemetry_samples')
    op.drop_index(op.f('ix_detection_events_started_at'), table_name='detection_events')
    op.drop_index('ix_detection_events_session_type', table_name='detection_events')
    op.drop_index('ix_detection_events_session_started', table_name='detection_events')
    op.drop_index(op.f('ix_detection_events_session_id'), table_name='detection_events')
    op.drop_index(op.f('ix_detection_events_event_type'), table_name='detection_events')
    op.drop_table('detection_events')
    op.drop_index(op.f('ix_user_settings_user_id'), table_name='user_settings')
    op.drop_table('user_settings')
    op.drop_index('ix_study_sessions_user_started', table_name='study_sessions')
    op.drop_index(op.f('ix_study_sessions_user_id'), table_name='study_sessions')
    op.drop_index(op.f('ix_study_sessions_status'), table_name='study_sessions')
    op.drop_index(op.f('ix_study_sessions_started_at'), table_name='study_sessions')
    op.drop_table('study_sessions')
    op.drop_index(op.f('ix_auth_identities_user_id'), table_name='auth_identities')
    op.drop_table('auth_identities')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
